Issue #1 feat: docker compose files for keycloak
project-sunbird/sunbird-auth pull request #2
Opened 2017-08-08 10:03 UTC by devops-ekstep

2017-08-09 05:36 UTC, devops-ekstep commented
@kochhar please review

2017-08-09 08:36 UTC, kochhar requested changes
@devops-ekstep I have noted comments for changes which need to be made. Please address these comments and resubmit the PR.

2017-08-11 09:12 UTC, kochhar commented on keycloak/themes/sunbird/login/keycloak/docker-compose.yml
> +      POSTGRES_PORT_5432_TCP_ADDR: keycloak_db
Postgres data should be encrypted and come from a secrets file.

2017-08-11 09:13 UTC, kochhar requested changes

2017-08-11 09:13 UTC, kochhar commented on keycloak/themes/sunbird/login/keycloak/docker-entrypoint.sh
> +KEYCLOAK_PASSWORD=ash12345678
Keycloak credentials should not be part of this script or this commit. It is a security hole.

2017-08-17 11:55 UTC, kochhar requested changes

2017-08-17 11:55 UTC, kochhar commented on keycloak/deploy/docker/README
> +docker build -t "keycloak_image:3.2.1.Final" .
@devops-ekstep aren't we currently using keycloak version 3.2.0.Final?

2017-08-17 11:55 UTC, kochhar commented on keycloak/deploy/docker/docker-entrypoint.sh
> +KEYCLOAK_PASSWORD=ash12345^&*()
passwords must be encrypted and vaulted.

2017-08-17 11:55 UTC, kochhar commented on keycloak/deploy/docker/docker-entrypoint.sh
> +exec /opt/jboss/keycloak/bin/standalone.sh -Djboss.bind.address.private=$HOSTNAME_IP $@
this seems to be conflicting syntax with the CMD provided in the dockerfile. 

I suggest that 
1. you move the computation of the $HOSTNAME_IP to the Dockerfile and 
2. Add -bprivate $HOSTNAME_IP as additional args in the CMD line.

2017-08-17 11:55 UTC, kochhar commented on keycloak/deploy/docker/Dockerfile
> +ADD docker-entrypoint.sh /opt/jboss/
Also need to change the standalone-ha.xml during the build to set
1. database configuration
1. logging configuration 
1. jgroups cluster configuration.

2017-08-17 11:55 UTC, kochhar commented on keycloak/deploy/docker/docker-entrypoint.sh
> +if [ $KEYCLOAK_USER ] && [ $KEYCLOAK_PASSWORD ]; then
This must only be executed when a new environment is being created for the first time. This cannot be executed every time.

2024-07-23 09:40 UTC, closed without merging